### ISSUE TITLE
Add a scenario around roles and permissions

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#251] opened 2018-11-19 07:52 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=1649961

Any role created prior to upgrade to 6.4, which contains a permission that has moved filters, will be "corrupt".  You cannot save changes to the role, until the bad filters are removed and recreated correctly, and add the new filters where the permissions currently reside, post 6.4 upgrade.

**Comment by ntkathole** [comment] 2019-11-17 15:50
Closing as dupe of #281

**Closed by ntkathole** 2019-11-17 15:50 UTC
Labels: High
